name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Bot On Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ADDRESS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: /home/afo/discordBOT/deploy.sh